spring.application.name=digistart-conteudo
server.port=8082

# Configuração do ShardingSphere
spring.shardingsphere.datasource.names=ds0

spring.shardingsphere.datasource.ds0.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds0.driver-class-name=org.postgresql.Driver
spring.shardingsphere.datasource.ds0.jdbc-url=jdbc:postgresql://localhost:5432/postgres
spring.shardingsphere.datasource.ds0.username=postgres
spring.shardingsphere.datasource.ds0.password=123

# Configuração das regras de sharding
spring.shardingsphere.rules.sharding.default-database-strategy.type=STANDARD
spring.shardingsphere.rules.sharding.default-database-strategy.standard.sharding-column=id
spring.shardingsphere.rules.sharding.default-database-strategy.standard.sharding-algorithm-name=database-inline

spring.shardingsphere.rules.sharding.sharding-algorithms.database-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.database-inline.props.algorithm-expression=ds0

# Configuração do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Habilitar o ShardingSphere
spring.shardingsphere.enabled=true
spring.shardingsphere.mode.type=Memory

spring.jackson.serialization.indent-output=true

# Configurações de Logging
logging.level.root=INFO
logging.level.DigiStart_Conteudo=DEBUG