-- Migration para criação da tabela modulos
-- Criada em: 2025-04-15
-- Descrição: Criação da tabela principal de módulos do sistema

CREATE TABLE IF NOT EXISTS modulos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(255) NULL,
    ativo BOOLEAN DEFAULT true NOT NULL,
    professor_id BIGINT NOT NULL
);
