-- Migration para criação da tabela aulas
-- Criada em: 2025-04-15
-- Descrição: Criação da tabela de aulas vinculadas aos módulos

CREATE TABLE IF NOT EXISTS aulas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) PRIMARY KEY,
    titulo VARCHAR(50) NOT NULL,
    descricao VARCHAR(255) NULL,
    video_url VARCHAR(255) NOT NULL,
    ordem INTEGER NOT NULL,
    ativa BOOLEAN DEFAULT true NOT NULL,
    modulo_id BIGINT NULL,
    
    CONSTRAINT aulas_modulo_id_fkey FOREIGN KEY (modulo_id) REFERENCES modulos(id) ON DELETE CASCADE
);
