-- Migration para criação da tabela progresso_aulas
-- Criada em: 2025-04-15
-- Descrição: Criação da tabela de progresso de aulas por aluno

CREATE TABLE IF NOT EXISTS progresso_aulas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) PRIMARY KEY,
    aluno_id BIGINT NOT NULL,
    aula_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    data_conclusao TIMESTAMP NULL,
    tempo_assistido_segundos BIGINT NULL,
    
    CONSTRAINT progresso_aulas_aula_id_fkey FOREIGN KEY (aula_id) REFERENCES aulas(id) ON DELETE CASCADE
);
